export const officialDecks = {
  'Base':"Base Set",
  'BaseUK':"Base Set (UK Edition)",
  'Box':"Box Expansion",
  'CAHe1':"The First Expansion",
  'CAHe2':"The Second Expansion",
  'CAHe3':"The Third Expansion",
  'CAHe4':"The Fourth Expansion",
  'CAHe5':"The Fifth Expansion",
  'CAHe6':"The Sixth Expansion",
  '90s': "90s Nostalgia Pack",
  'Canadian':"Canadian",
  'fantasy':"Fantasy Pack",
  'food':"Food Pack",
  'greenbox':"Green Box Expansion",
  'misprint':"Misprint Replacement Bonus Cards",
  'reject':"Reject Pack",
  'reject2':"Reject Pack 2",
  'science':"Science Pack",
  'www':"World Wide Web Pack",
}
